// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inbox struct {
	ConsumerName       string
	MessageID          string
	PayloadHash        []byte
	WagerTransactionID pgtype.UUID
	ReceivedAt         pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}

type Outbox struct {
	EventID       pgtype.UUID
	EventType     string
	EventVersion  int32
	AggregateType string
	AggregateID   pgtype.UUID
	CorrelationID string
	CausationID   pgtype.Text
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	ClaimedBy     pgtype.Text
	ClaimToken    pgtype.UUID
	ClaimedUntil  pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	LastError     pgtype.Text
}

type WagerTransaction struct {
	ID                             pgtype.UUID
	Origin                         string
	ProviderID                     pgtype.Text
	ExternalTransactionID          pgtype.Text
	IdempotencyKey                 pgtype.Text
	PayloadHash                    []byte
	WalletID                       pgtype.UUID
	PlayerID                       pgtype.UUID
	RoundID                        pgtype.Text
	GameID                         pgtype.Text
	Kind                           string
	AmountMinor                    int64
	Currency                       string
	ReferenceExternalTransactionID pgtype.Text
	ReferenceTransactionID         pgtype.UUID
	Status                         string
	FailureCode                    pgtype.Text
	ResultBalanceMinor             pgtype.Int8
	ResultCurrency                 pgtype.Text
	ResultWalletVersion            pgtype.Int8
	CorrelationID                  string
	CausationID                    pgtype.Text
	ReferenceAttempts              int32
	NextReferenceAttemptAt         pgtype.Timestamptz
	ReferenceClaimedBy             pgtype.Text
	ReferenceClaimToken            pgtype.UUID
	ReferenceClaimedUntil          pgtype.Timestamptz
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
	CompletedAt                    pgtype.Timestamptz
}

type Wallet struct {
	ID           pgtype.UUID
	PlayerID     pgtype.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WalletLedgerEntry struct {
	ID                 pgtype.UUID
	WalletID           pgtype.UUID
	TransactionID      pgtype.UUID
	Direction          string
	AmountMinor        int64
	Currency           string
	BalanceBeforeMinor int64
	BalanceAfterMinor  int64
	CreatedAt          pgtype.Timestamptz
}
