// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AllocateID(ctx context.Context) (string, error)
	GetWallet(ctx context.Context, id pgtype.UUID) (GetWalletRow, error)
	GetWalletForUpdate(ctx context.Context, id pgtype.UUID) (GetWalletForUpdateRow, error)
}

var _ Querier = (*Queries)(nil)
