// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateID = `-- name: AllocateID :one
SELECT uuidv7()::text AS id
`

func (q *Queries) AllocateID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, allocateID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getWallet = `-- name: GetWallet :one
SELECT id::text AS id,player_id::text AS player_id,balance_minor,currency,version,created_at,updated_at
FROM wallet WHERE id=$1
`

type GetWalletRow struct {
	ID           string
	PlayerID     string
	BalanceMinor int64
	Currency     string
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetWallet(ctx context.Context, id pgtype.UUID) (GetWalletRow, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i GetWalletRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.BalanceMinor,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id::text AS id,player_id::text AS player_id,balance_minor,currency,version,created_at,updated_at
FROM wallet WHERE id=$1 FOR UPDATE
`

type GetWalletForUpdateRow struct {
	ID           string
	PlayerID     string
	BalanceMinor int64
	Currency     string
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetWalletForUpdate(ctx context.Context, id pgtype.UUID) (GetWalletForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i GetWalletForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.BalanceMinor,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
